/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-tertiary": "#e5fff2",
              "secondary-dim": "#465468",
              "error": "#9f403d",
              "on-primary-fixed-variant": "#515c70",
              "tertiary": "#2c6a55",
              "tertiary-fixed-dim": "#aaead0",
              "error-container": "#fe8983",
              "on-secondary": "#f8f8ff",
              "primary-container": "#d8e3fb",
              "on-primary": "#f6f7ff",
              "background": "#f7f9fb",
              "surface-container": "#e8eff3",
              "outline": "#717c82",
              "tertiary-dim": "#1d5d49",
              "secondary-fixed": "#d5e3fc",
              "on-tertiary-fixed-variant": "#2e6b57",
              "on-tertiary-fixed": "#074e3b",
              "primary-dim": "#485367",
              "primary-fixed": "#d8e3fb",
              "primary-fixed-dim": "#cad5ed",
              "surface-dim": "#cfdce3",
              "inverse-surface": "#0b0f10",
              "surface-container-high": "#e1e9ee",
              "on-surface-variant": "#566166",
              "primary": "#545f73",
              "on-secondary-container": "#455367",
              "surface-tint": "#545f73",
              "on-surface": "#2a3439",
              "on-secondary-fixed-variant": "#4e5c71",
              "surface-container-lowest": "#ffffff",
              "secondary": "#526074",
              "on-error-container": "#752121",
              "error-dim": "#4e0309",
              "secondary-container": "#d5e3fc",
              "surface-container-highest": "#d9e4ea",
              "surface-bright": "#f7f9fb",
              "on-primary-fixed": "#354053",
              "surface": "#f7f9fb",
              "on-background": "#2a3439",
              "on-tertiary-container": "#22614d",
              "surface-container-low": "#f0f4f7",
              "surface-variant": "#d9e4ea",
              "on-error": "#fff7f6",
              "inverse-primary": "#dae6fe",
              "inverse-on-surface": "#9a9d9f",
              "tertiary-fixed": "#b8f9de",
              "on-secondary-fixed": "#324053",
              "on-primary-container": "#475266",
              "outline-variant": "#a9b4b9",
              "secondary-fixed-dim": "#c7d5ed",
              "tertiary-container": "#b8f9de"
          },
          "borderRadius": {
              "DEFAULT": "0.375rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
          }
      }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
